<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(ToolsTfm)</TargetFramework>
    <RootNamespace>Sohan.Tools</RootNamespace>
    <AssemblyName>sohan</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sohan.Core\Sohan.Core.csproj" />
    <ProjectReference Include="..\Sohan.Data\Sohan.Data.csproj" />
  </ItemGroup>
</Project>
