using System.Globalization;
using System.Text;
using Kiln.Data.Definitions;
using Kiln.Data.Loading;

namespace Kiln.Tools.Commands;

/// <summary>
/// Turns content ids into compile-time constants, so gameplay code says
/// <c>Ids.Items.WpnIronSword</c> instead of a magic string. Renaming or deleting content
/// then breaks the build instead of failing silently at runtime.
/// </summary>
public static class CodegenCommand
{
    public static int Run(string[] args)
    {
        var dataRoot = Program.ResolveDataRoot(args);
        var outPath = Program.OptionValue(args, "--out")
                      ?? Path.Combine(dataRoot, "..", "..", "src", "Kiln.Data", "Generated", "Ids.g.cs");
        outPath = Path.GetFullPath(outPath);

        var check = Program.HasFlag(args, "--check");

        var load = ContentLoader.LoadFromDirectory(dataRoot);
        if (load.Errors.Count > 0)
        {
            Console.Error.WriteLine("Cannot generate ids while content fails to load. Run 'validate' first.");
            return 1;
        }

        var generated = Generate(load.Database);

        if (check)
        {
            if (!File.Exists(outPath))
            {
                Console.Error.WriteLine($"FAILED: {Short(outPath)} does not exist. Run: dotnet run --project src/Kiln.Tools -- codegen");
                return 1;
            }

            var existing = File.ReadAllText(outPath).ReplaceLineEndings("\n");
            if (existing != generated.ReplaceLineEndings("\n"))
            {
                Console.Error.WriteLine(
                    $"FAILED: {Short(outPath)} is out of date.\n" +
                    "Run: dotnet run --project src/Kiln.Tools -- codegen  (and commit the result)");
                return 1;
            }

            Console.WriteLine($"OK: {Short(outPath)} is up to date.");
            return 0;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, generated);
        Console.WriteLine($"Wrote {Short(outPath)}");
        return 0;
    }

    private static string Generate(ContentDatabase db)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by: dotnet run --project src/Kiln.Tools -- codegen");
        sb.AppendLine("//     Do not edit by hand. Edit the JSON under game/data/ and re-run.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace Kiln.Data;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Compile-time constants for every content id.</summary>");
        sb.AppendLine("public static class Ids");
        sb.AppendLine("{");

        Section(sb, "Items", db.Items.Keys);
        Section(sb, "Enemies", db.Enemies.Keys);
        Section(sb, "Skills", db.Skills.Keys);
        Section(sb, "Quests", db.Quests.Keys);
        Section(sb, "DropTables", db.DropTables.Keys);
        Section(sb, "BonusPools", db.BonusPools.Keys);
        Section(sb, "UpgradePaths", db.UpgradePaths.Keys);
        Section(sb, "Visuals", db.Visuals.Keys);
        Section(sb, "Shards", db.Shards.Keys);
        Section(sb, "Zones", db.Zones.Keys);
        Section(sb, "KitPieces", db.KitPieces.Keys);

        sb.AppendLine("}");
        return sb.ToString().ReplaceLineEndings("\n");
    }

    private static void Section(StringBuilder sb, string name, IEnumerable<string> ids)
    {
        var ordered = ids.Order(StringComparer.Ordinal).ToList();

        sb.AppendLine($"    public static class {name}");
        sb.AppendLine("    {");

        if (ordered.Count == 0)
        {
            sb.AppendLine("        // (none yet)");
        }
        else
        {
            foreach (var id in ordered)
            {
                sb.AppendLine($"        public const string {ToPascal(id)} = \"{id}\";");
            }

            sb.AppendLine();
            sb.AppendLine($"        public static readonly string[] All = [{string.Join(", ", ordered.Select(i => $"\"{i}\""))}];");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string ToPascal(string id)
    {
        var sb = new StringBuilder(id.Length);
        var upper = true;

        foreach (var c in id)
        {
            if (c == '_')
            {
                upper = true;
                continue;
            }

            sb.Append(upper ? char.ToUpper(c, CultureInfo.InvariantCulture) : c);
            upper = false;
        }

        // A C# identifier cannot start with a digit.
        if (sb.Length > 0 && char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    private static string Short(string path)
    {
        var norm = path.Replace('\\', '/');
        var i = norm.IndexOf("/src/", StringComparison.Ordinal);
        return i >= 0 ? norm[(i + 1)..] : norm;
    }
}
